# This is a basic workflow to help you get started with Actions

name: NewCI
# Controls when the workflow will run
# Triggers the workflow on push or pull request events but only for the main branch
on: [push, pull_request, workflow_dispatch]

# Allows you to run this workflow manually from the Actions tab


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout the code from the repository
        uses: actions/checkout@v2
        
      - name: Create local.properties
        run: echo "MAPS_API_KEY=empty" > local.properties

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean Gradle
        run: ./gradlew clean

      - name: Build with Gradle
        run: ./gradlew build

      - name: Run Unit Test with Gradle
        run: ./gradlew test
        
      - name: Sends message to Slack channel
        if: always()
        uses: 8398a7/action-slack@v3.9.0
        with:
          status: ${{ job.status }}
          author_name: P1_4_Intergration
          fields: repo,commit,message,author # default: repo,commit
        env:
          # Need dedicated webhook URL that receives and post to a specific channel
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
